all:
  hosts:
    pi:
      ansible_host: raspberrypi.local
      ansible_user: pi
      ansible_ssh_pass: raspberry
      ansible_become: True
  vars:
    unattended_upgrades__auto_reboot: True
    transmission_download_dir: /srv/downloads
    transmission_incomplete_dir: /srv/downloads
    transmission_incomplete_dir_enabled: True
    transmission_rpc_whitelist: "192.168.0.*"
    transmission_user: "{{ ansible_user }}"
    transmission_watch_dir: /srv/torrents
    samba_users:
      - name: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
    samba_config_file: smb.conf
