all:
  hosts:
    pi:
      ansible_host: raspberrypi.local
      ansible_user: pi
      ansible_ssh_pass: raspberry
      ansible_become: True
  vars:
    packages:
      - p7zip-full
      - rpi-eeprom
    unattended_upgrades__auto_reboot: True
    transmission_download_dir: /srv/downloads
    transmission_rpc_whitelist: "192.168.0.*"
    transmission_user: "{{ ansible_user }}"
    transmission_watch_dir: /srv/torrents
    tmux_users:
      - pi
    samba_users:
      - name: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
    samba_config_file: smb.conf
    mopidy_packages:
      - mopidy-local-sqlite
    mopidy_pip: []
    mopidy_media_dir: '/srv/music'
    mopidy_local_scan: daily
    mopidy_settings:
      - { section: 'http', option: 'hostname', value: '::' }
      - { section: 'mpd', option: 'hostname', value: '::' }
      - { section: 'local', option: 'library', value: 'sqlite' }
      - { section: 'local', option: 'scan_flush_threshold', value: '100' }
      - { section: 'local', option: 'media_dir', value: '{{ mopidy_media_dir }}' }
      - { section: 'local', option: 'scan_timeout', value: '2000' }
      - { section: 'file', option: 'media_dirs', value: '{{ mopidy_media_dir }}' }
      - { section: 'm3u', option: 'playlists_dir', value: '{{ mopidy_media_dir }}/playlists' }
    hifiberry_enabled: False
