all:
  hosts:
    pi:
      ansible_host: raspberrypi.local
      ansible_user: pi
      ansible_ssh_pass: raspberry
      ansible_become: True
  vars:
    unattended_upgrades__auto_reboot: True
    transmission_rpc_whitelist: "192.168.0.*"
    transmission_download_dir: /srv/downloads
    transmission_watch_dir: /srv/torrents
